branches:
    only:
    - master
    - staging
    - trying
    - /^release\/.*$/ # release branches
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

env:
    global:
        - JULIA_DEBUG="all"

git:
    depth: 99999999

julia:
    - "1.1"

language: julia

matrix:
    allow_failures:
        - julia: "nightly"
        - os: osx
fast_finish: true

notifications:
    email:
        on_success: never # default: change
        on_failure: always # default: always

os:
    - linux
#     - osx

############################################################################

before_install:
    - true
install:
    - true
before_script:
    - true
script:
    - true
after_script:
    - true

############################################################################

stages:
    - "Compatibility"
    - "Test"

############################################################################

jobs:
    include:
        - stage: "Compatibility"
          os: linux
          julia: 1.1
          env:
              - GROUP="Compatibility"
          script: ./ci/travis/compatibility.sh
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - GROUP="Test"
              - JULIA_DEBUG="all"
              - PREDICTMDFULL_IMPORT_ALL="true"
          script: ./ci/travis/script.sh
        - stage: "Test"
          os: linux
          julia: 1.1
          env:
              - GROUP="Test"
              - JULIA_DEBUG="all"
              - PREDICTMDFULL_IMPORT_ALL="false"
          script: ./ci/travis/script.sh
