##### Beginning of file

import Pkg

function _package_list()::Vector{String}
    project_toml::String = package_directory("Project.toml",)
    package_list::Vector{String} = sort(
        unique(
            strip.(
                collect(
                    keys(Pkg.TOML.parsefile(project_toml)["deps"])
                    )
                )
            )
        )
    return package_list
end

function _print_list_of_package_imports(io::IO = stdout)::Nothing
    package_list::Vector{String} = sort(unique(_package_list()))
    using_instead_of_import::Vector{String} = String[
        "Distributed",
        ]
    println("##### Beginning of file")
    println()
    println("# Automatically generated by: ")
    println("# PredictMDFull._print_list_of_package_imports()")
    println()
    for i = 1:length(package_list)
        name::String = package_list[i]
        if name in using_instead_of_import
            println(io, "using $(name)",)
        else
            println(io, "import $(name)",)
        end
    end
    println()
    println("##### End of file")
    println()
    return nothing
end

##### End of file
